version: '3'
services:
  service_mysql_5.7:
    image: mysql:5.7
    container_name: service_mysql_5.7
    command: ["--default-authentication-plugin=mysql_native_password"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - service-mysql-data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    ports:
      - "${MYSQL_PORT}:3057"
    networks:
      - my-net
volumes:
  service-mysql-data:

networks:
  my-net:
    external:
      name: 'my-network'