services:
  service_mysql_5.7:
    image: mysql:5.7.38
    container_name: service_mysql_5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - service-mysql-data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    ports:
      - "${MYSQL_PORT}:3057"
volumes:
  service-mysql-data: