services:
  service_memcached:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: service_memcached_1.5
    ports:
      - "${MEMCACHED_PORT}:11211"
    restart: always
networks:
  default:
    name: services_network
    external: true