version: '3'
services:
  service_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: service_phpmyadmin
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
volumes:
  service-phpmyadmin-data:
networks:
  default:
    name: services_network
    external: true