version: '3'
services:
  service_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: service_phpmyadmin
    environment:
      PMA_HOST: 192.168.1.8
      PMA_PORT: 33001
    restart: always
    ports:
      - "${PHPMYADMIN_PORT}:80"
volumes:
  service-phpmyadmin-data: