services:
  service_mysql_8.0:
    image: mysql:8.0.28
    container_name: service_mysql_8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - service-mysql-data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./init/:/docker-entrypoint-initdb.d/
    ports:
      - "${MYSQL_PORT}:3080"
volumes:
  service-mysql-data:
networks:
  default:
    name: services_network
    external: true