version: '3'
services:
  service_mysql:
    image: mysql:8.0
    container_name: service_mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - service-mysql-data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - service
volumes:
  service-mysql-data:
networks:
  service:
    driver: bridge