services:
  service_redis:
    image: redis:7.0-bullseye
    restart: always
    container_name: service_redis_7.0
    ports:
      - "${REDIS_PORT}:6379"
volumes:
  service-redis-data:
networks:
  default:
    name: services_network
    external: true